### ISSUE TITLE
Chrash under Amiga OS3.2.2.1

### ISSUE THREAD

**Issue by Zettmaster** [midwan/host-run#2]
On Pi400 with Amiberry 5.6.7 and Amiga OS3.2.2.1 will host-run work, but after start Chromium over the Shell and open YouTube, Amiberry chrash and close. Chromium leave still open in Linux. OS3.2 alone run very stable.

**Comment by midwan** [comment]
I cannot recreate this, what distro are you testing this on? I've tested it on Manjaro Linux (64-bit) and the official RPI-OS (64-bit), on both Pi400 and RPI5, seems to work as expected.

In either case, I don't think this is an issue with `host-run`, since it's job finishes as soon as it has launched the command you requested (Chrome in this case).

**Comment by Zettmaster** [comment]
Hello, it's Debian 11 and i think than it's a Problem of os3.2 with the new
Rom 47.111. Host-run open this application and the chrash follow later.
Under Pimiga 4 and OS3.9 with kick 3.1 ist no chrash.

Greetings from germany

Dimitris Panokostas ***@***.***> schrieb am Di., 27. Feb.
2024, 21:18:

**Comment by midwan** [comment]
@Zettmaster 
I still can't recreate this, at least not in my environment.
I tried with AmigaOS 3.2.2.1 with the latest kickstart also, doesn't make a difference.
I can launch `chromium-browser` from a shell using `host-run`, visit Youtube and play a few videos normally, without anything crashing here.

It must be something else that's causing it for you, but it would be good to narrow it down. Still, I think this issue doesn't belong to this repo (which is about `host-run`), since the tool seems to work fine and doesn't crash itself (since it launches Chromium, even in your case). Whatever triggers the crash comes afterwards, and it's unrelated to `host-run` I think.

Perhaps it's best if we move this to the Amiberry repo instead?

**Comment by Zettmaster** [comment]
Yes, please! I have no Idea what Amiberry brings to Close. Thank you!

Dimitris Panokostas ***@***.***> schrieb am Di., 27. Feb.
2024, 23:07:

**Comment by Zettmaster** [comment]
Hello,

i have found the solution. It was in the Amiberry settings in CPU/FPU
compatibility Mode checkbox selected by FPU...only JIT works now.

Sorry... greetings

En Rico ***@***.***> schrieb am Di., 27. Feb. 2024, 23:16:
